// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: media.proto

package protobuf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UploadMediaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadMediaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadMediaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadMediaRequestMultiError, or nil if none found.
func (m *UploadMediaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadMediaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetDir()) < 1 {
		err := UploadMediaRequestValidationError{
			field:  "Dir",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetFilename()) < 1 {
		err := UploadMediaRequestValidationError{
			field:  "Filename",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetFileContent()) < 1 {
		err := UploadMediaRequestValidationError{
			field:  "FileContent",
			reason: "value length must be at least 1 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UploadMediaRequestMultiError(errors)
	}

	return nil
}

// UploadMediaRequestMultiError is an error wrapping multiple validation errors
// returned by UploadMediaRequest.ValidateAll() if the designated constraints
// aren't met.
type UploadMediaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadMediaRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadMediaRequestMultiError) AllErrors() []error { return m }

// UploadMediaRequestValidationError is the validation error returned by
// UploadMediaRequest.Validate if the designated constraints aren't met.
type UploadMediaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadMediaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadMediaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadMediaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadMediaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadMediaRequestValidationError) ErrorName() string {
	return "UploadMediaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadMediaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadMediaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadMediaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadMediaRequestValidationError{}

// Validate checks the field values on UploadMediaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadMediaResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadMediaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadMediaResponseMultiError, or nil if none found.
func (m *UploadMediaResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadMediaResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	// no validation rules for Filename

	// no validation rules for Id

	if len(errors) > 0 {
		return UploadMediaResponseMultiError(errors)
	}

	return nil
}

// UploadMediaResponseMultiError is an error wrapping multiple validation
// errors returned by UploadMediaResponse.ValidateAll() if the designated
// constraints aren't met.
type UploadMediaResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadMediaResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadMediaResponseMultiError) AllErrors() []error { return m }

// UploadMediaResponseValidationError is the validation error returned by
// UploadMediaResponse.Validate if the designated constraints aren't met.
type UploadMediaResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadMediaResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadMediaResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadMediaResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadMediaResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadMediaResponseValidationError) ErrorName() string {
	return "UploadMediaResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UploadMediaResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadMediaResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadMediaResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadMediaResponseValidationError{}
