// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: media.proto

package protobuf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _media_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on UploadMediaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UploadMediaRequest) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetDir()) < 1 {
		return UploadMediaRequestValidationError{
			field:  "Dir",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetFilename()) < 1 {
		return UploadMediaRequestValidationError{
			field:  "Filename",
			reason: "value length must be at least 1 runes",
		}
	}

	if len(m.GetFileContent()) < 1 {
		return UploadMediaRequestValidationError{
			field:  "FileContent",
			reason: "value length must be at least 1 bytes",
		}
	}

	return nil
}

// UploadMediaRequestValidationError is the validation error returned by
// UploadMediaRequest.Validate if the designated constraints aren't met.
type UploadMediaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadMediaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadMediaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadMediaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadMediaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadMediaRequestValidationError) ErrorName() string {
	return "UploadMediaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadMediaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadMediaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadMediaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadMediaRequestValidationError{}

// Validate checks the field values on UploadMediaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UploadMediaResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Url

	// no validation rules for Filename

	return nil
}

// UploadMediaResponseValidationError is the validation error returned by
// UploadMediaResponse.Validate if the designated constraints aren't met.
type UploadMediaResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadMediaResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadMediaResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadMediaResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadMediaResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadMediaResponseValidationError) ErrorName() string {
	return "UploadMediaResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UploadMediaResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadMediaResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadMediaResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadMediaResponseValidationError{}
